name: Hanoi's Tower | CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Change directory
        run: cd hanoi-tower/hanoi-tower-solver
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
